// Generated by CoffeeScript 1.7.1

/*
Grid: for entities that might want to snap to a grid.
 */

(function() {
  Crafty.c("Grid", {
    init: function() {
      this.attr({
        w: Game.map_grid.tile.width,
        h: Game.map_grid.tile.height
      });
    },
    at: function(x, y) {
      if (x === undefined && y === undefined) {
        return {
          x: this.x / Game.map_grid.tile.width,
          y: this.y / Game.map_grid.tile.height
        };
      } else {
        this.attr({
          x: x * Game.map_grid.tile.width,
          y: y * Game.map_grid.tile.height
        });
        return this;
      }
    }
  });


  /*
  Actor: shorthand for 2D entities using a grid.
   */

  Crafty.c("Actor", {
    init: function() {
      this.requires("2D, Canvas, Grid");
    }
  });


  /*
  Train: moves along track, contains movement logic.
   */

  Crafty.c("Train", {
    init: function() {
      this.requires((window.HEADLESS_MODE ? "2D, Grid" : "Actor, Keyboard"));
      this.speed = Constants.FULL_SPEED;
      this.playerOne = false;
      this.angle = 0;
      this.curveCommandEnabled = false;
      this.progress = 0;
      this.targetDirection;
      this.sourceDirection;
      this.distanceTraveled = 0;
    },
    checkCollision: function() {
      var collisionFound, other;
      other = this;
      collisionFound = false;
      Crafty("Train").each(function() {
        if (this.playerOne !== other.playerOne) {
          if (Math.sqrt((other.x - this.x) * (other.x - this.x)) + Math.sqrt((other.y - this.y) * (other.y - this.y)) < Constants.COLLISION_SIZE) {
            collisionFound = true;
          }
        }
      });
      return collisionFound;
    },
    findTrack: function() {
      var currentTrack;
      currentTrack = Util.trackAt(this.at().x, this.at().y);
      this.currentTrack = currentTrack;
      this.angle = Util.endAngle(currentTrack.dir[1]);
      return this;
    },
    isCurving: function() {
      return this.sourceDirection !== this.targetDirection;
    },
    _finishSection: function(dir) {
      if (this.reversing) {
        if (true && !(this._hasCurveOption() && this._hasStraightOption()) && this.currentTrack.dir.length === 3) {
          this.curves.push(this._hasCurveOption());
        }
      }
      this.angle = Util.endAngle(dir);
      this.x = this.currentTrack.x + Util.dirx(dir) * Constants.TILE_HALF;
      this.y = this.currentTrack.y + Util.diry(dir) * Constants.TILE_HALF;
      this.sourceDirection = this.targetDirection;
      this._updateCurrentTrack(dir);
      if (this._arriveAtStation != null) {
        this._arriveAtStation();
      }
    },
    _hasStraightOption: function() {
      return this.currentTrack.dir.indexOf(this.sourceDirection) > -1;
    },
    _hasCurveOption: function() {
      return this.currentTrack.dir.length === 3 && (this.currentTrack.dir.indexOf(Util.opposite(this.sourceDirection)) > 0) || this.currentTrack.dir.length === 2 && this.currentTrack.dir.indexOf(this.sourceDirection) === -1;
    },
    moveAlongTrack: function(dist) {
      var remainingTries, temp;
      this.distanceTraveled += dist;
      this.reversing = dist < 0;
      if (this.reversing) {
        this.angle = this.angle + Math.PI;
        if (this.isCurving()) {
          this.progress = Constants.TILE_HALF * Math.PI / 2 - this.progress;
        } else {
          this.progress = -this.progress;
        }
        dist = -dist;
        temp = this.sourceDirection;
        this.sourceDirection = Util.opposite(this.targetDirection);
        this.targetDirection = Util.opposite(temp);
      }
      this.remainingDist = dist;
      remainingTries = Constants.TILE_JUMP_LIMIT;
      this._removeSpriteComponent();
      this._addSpriteComponent();
      while (this.remainingDist > 0 && remainingTries-- > 0) {
        if (this.isCurving()) {
          this._moveCurved();
        } else {
          this._moveStraight();
        }
      }
      if (this.lightLayer) {
        this.lightLayer.attr({
          x: this.x,
          y: this.y
        });
      }
      if (this.reversing) {
        this.angle = this.angle - Math.PI;
        temp = this.sourceDirection;
        this.sourceDirection = Util.opposite(this.targetDirection);
        this.targetDirection = Util.opposite(temp);
        if (this.isCurving()) {
          this.progress = Constants.TILE_HALF * Math.PI / 2 - this.progress;
        } else {
          this.progress = -this.progress;
        }
      }
    },
    _moveStraight: function() {
      this.progress = Util.dirx(this.sourceDirection) * (this.x - this.currentTrack.x) + Util.diry(this.sourceDirection) * (this.y - this.currentTrack.y);
      if (this.progress < Constants.TILE_HALF - this.remainingDist) {
        this.move(this.sourceDirection, this.remainingDist);
        this.remainingDist = 0;
      } else {
        this._finishSection(this.sourceDirection);
        this.remainingDist -= Constants.TILE_HALF - this.progress;
        this.progress = 0;
      }
    },
    _moveCurved: function() {
      var angularDiff, counterClockwise, _ref;
      counterClockwise = ((_ref = this.sourceDirection + this.targetDirection) === "en" || _ref === "nw" || _ref === "ws" || _ref === "se" ? -1 : 1);
      angularDiff = 1 / (Constants.TILE_HALF * 2) * this.remainingDist * counterClockwise;
      if (this.progress < Constants.CURVE_QUARTER - this.remainingDist) {
        this.angle += angularDiff;
        this.x += Math.cos(this.angle) * (Math.sin(angularDiff) * (Constants.TILE_HALF * 2)) * counterClockwise;
        this.y += Math.sin(this.angle) * (Math.sin(angularDiff) * (Constants.TILE_HALF * 2)) * counterClockwise;
        this.progress += this.remainingDist;
        this.angle += angularDiff;
        this.remainingDist = 0;
      } else {
        this._finishSection(this.targetDirection);
        this.remainingDist -= Constants.CURVE_QUARTER - this.progress;
        this.progress = 0;
      }
    }
  });


  /*
  TrainHead: the first car of a train. Master of the movement of its train.
   */

  Crafty.c("TrainHead", {
    init: function() {
      this.requires("Train");
      this.passengers = 0;
      this.delivered = 0;
      this.followers = [];
      if (!window.HEADLESS_MODE) {
        this.lightLayer = Crafty.e("2D, Canvas, LightLayer").attr({
          z: 1000
        });
      }
    },
    _addSpriteComponent: function(dir) {
      if (!window.HEADLESS_MODE) {
        this.addComponent("spr_" + (this.playerOne ? "r" : "b") + "train" + (this.isCurving() && this.progress > Constants.TILE_HALF * Math.PI / 4 ? this.targetDirection : this.sourceDirection));
        this.lightLayer.addComponent("spr_" + (this.playerOne ? "r" : "b") + "train" + (this.isCurving() && this.progress > Constants.TILE_HALF * Math.PI / 4 ? this.targetDirection : this.sourceDirection) + "light");
      }
    },
    _removeSpriteComponent: function() {
      var baseSpriteName, i;
      if (!window.HEADLESS_MODE) {
        baseSpriteName = "spr_" + (this.playerOne ? "r" : "b") + "train";
        for (i in Constants.DIR_PREFIXES) {
          this.removeComponent(baseSpriteName + Constants.DIR_PREFIXES[i], false);
          this.lightLayer.removeComponent(baseSpriteName + Constants.DIR_PREFIXES[i] + "light", false);
        }
      }
    },
    _setBraking: function(braking) {
      var playerOne;
      if (braking) {
        if (!this.arrow) {
          this.arrow = Crafty.e("DirectionArrow").attr({
            x: this.x,
            y: this.y - 30
          }).attr({
            target: this
          });
        }
      } else {
        if (this.arrow) {
          this.arrow.destroy();
          this.arrow = null;
        }
      }
      this.curveCommandEnabled = braking;
      playerOne = this.playerOne;
      if (window.Brakes) {
        return Crafty("Train").each(function() {
          if (this.playerOne === playerOne) {
            return this.speed = (braking ? Constants.REDUCED_SPEED : Constants.FULL_SPEED);
          }
        });
      }
    },
    isBraking: function() {
      return this.speed === Constants.REDUCED_SPEED;
    }
  });


  /*
  CarryingTrain: a train that "carries" passengers. Data is still stored in the TrainHead.
   */

  Crafty.c("CarryingTrain", {
    init: function() {
      this.requires("Train");
      this.trans = [];
      return this.inStation = false;
    },
    _arriveAtStation: function() {
      var droppedOff, passengersGained, station, x;
      station = this.currentTrack.station;
      if (this.currentTrack.station) {
        if (this.inStation) {
          droppedOff = this._dropoff(station);
          passengersGained = this._pickup(station);
          this._assignDestinations(passengersGained, station, this.playerOne);
          this._updateStationSprites();
          x = droppedOff + passengersGained;
          if (window.GameClock.hour) {
            this.trans.push([((window.GameClock.hour - 6) * 60) + window.GameClock.minute, passengersGained, droppedOff]);
          }
          switch (false) {
            case !(x > 40):
              Crafty.audio.play("get3");
              break;
            case !(x > 20):
              Crafty.audio.play("get2");
              break;
            case !(x > 2):
              Crafty.audio.play("get1");
          }
          if (window.StationStop) {
            this.head.stayDelay = 60;
          }
          this.inStation = false;
        } else {
          this.inStation = true;
        }
      } else {
        this.inStation = false;
      }
    },
    _dropoff: function(station) {
      var deliveries;
      deliveries = (this.playerOne ? station.dropoffP1 : station.dropoffP2);
      this.head.passengers -= deliveries;
      this.head.delivered += deliveries;
      if (this.playerOne) {
        station.dropoffP1 = 0;
      } else {
        station.dropoffP2 = 0;
      }
      return deliveries;
    },
    _pickup: function(station) {
      var overflow, pickup, room;
      room = Constants.MAX_PASSENGERS - this.head.passengers;
      overflow = station.population - room;
      pickup = (overflow > 0 ? Constants.MAX_PASSENGERS - this.head.passengers : station.population);
      station.population = (overflow > 0 ? overflow : 0);
      this.head.passengers += pickup;
      return pickup;
    },
    _assignDestinations: function(passengers, boardedAtStation, onPlayerOne) {
      var target, targetCount;
      targetCount = Crafty("Station").length;
      while (passengers > 0) {
        target = Crafty(Crafty("Station")[Math.floor(Math.random() * targetCount)]);
        if (target !== boardedAtStation) {
          if (onPlayerOne) {
            target.dropoffP1++;
          } else {
            target.dropoffP2++;
          }
          passengers--;
        }
      }
    },
    _updateStationSprites: function() {
      Crafty("Station").each(function() {
        return this.updateSprites();
      });
      return Crafty("PlayerScore").each(function() {
        return this.update();
      });
    }
  });


  /*
  PlayerTrain: a train controlled by a player.
   */

  Crafty.c("PlayerTrain", {
    init: function() {
      return this.requires("TrainHead");
    },
    _updateCurrentTrack: function(dir) {
      var backThroughCurve, curve, f, isCurving, straight, _i, _j, _len, _len1, _ref, _ref1;
      backThroughCurve = this.reversing && !(this._hasCurveOption() && this._hasStraightOption()) && this.currentTrack.dir.length === 3;
      if (backThroughCurve) {
        _ref = this.followers;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          f = _ref[_i];
          f.curves.shift();
        }
      }
      this.currentTrack = Util.trackAt(this.currentTrack.at().x + Util.dirx(dir), this.currentTrack.at().y + Util.diry(dir));
      straight = this._hasStraightOption();
      curve = this._hasCurveOption();
      this.targetDirection = ((straight && curve && this.curveCommandEnabled) || (curve && !straight) ? Util.getTargetDirection(this.currentTrack, this.sourceDirection) : this.sourceDirection);
      if (straight && curve) {
        isCurving = this.isCurving();
        _ref1 = this.followers;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          f = _ref1[_j];
          f.curves.push(isCurving);
        }
      }
    },
    bindKeyboardTurn: function(keyCode) {
      if (keyCode != null) {
        this.bind("KeyDown", (function(e) {
          return function(e) {
            if (e.keyCode === keyCode && GameState.running) {
              Crafty.audio.play('brakeson');
              return this._setBraking(true);
            }
          };
        })(keyCode));
        this.bind("KeyUp", (function(e) {
          return function(e) {
            if (e.keyCode === keyCode && GameState.running) {
              Crafty.audio.play('brakesoff');
              return this._setBraking(false);
            }
          };
        })(keyCode));
        return this;
      }
    }
  });


  /*
  FollowTrain: a train car that follows a TrainHead or another FollowTrain.
   */

  Crafty.c("FollowTrain", {
    init: function() {
      this.requires("Train");
      this.curves = [];
      if (!window.HEADLESS_MODE) {
        this.lightLayer = Crafty.e("2D, Canvas, LightLayer").attr({
          z: 1000
        });
      }
    },
    _addSpriteComponent: function() {
      var dir, spriteName;
      if (!window.HEADLESS_MODE) {
        dir = (this.isCurving() && this.progress > Constants.TILE_HALF * Math.PI / 4 ? this.targetDirection : this.sourceDirection);
        spriteName = "spr_" + (this.playerOne ? "r" : "b") + "train" + (dir === "n" || dir === "s" ? "side" : "");
        this.addComponent(spriteName);
        this.lightLayer.addComponent(spriteName + "light");
      }
    },
    _removeSpriteComponent: function() {
      var baseSpriteName;
      if (!window.HEADLESS_MODE) {
        baseSpriteName = "spr_" + (this.playerOne ? "r" : "b") + "train";
        this.removeComponent(baseSpriteName, false).removeComponent(baseSpriteName + "side", false);
        this.lightLayer.removeComponent(baseSpriteName + "light", false).removeComponent(baseSpriteName + "sidelight", false);
      }
    },
    _updateCurrentTrack: function(dir) {
      var curve, straight;
      this.currentTrack = Util.trackAt(this.currentTrack.at().x + Util.dirx(dir), this.currentTrack.at().y + Util.diry(dir));
      curve = this._hasCurveOption();
      straight = this._hasStraightOption();
      this.targetDirection = ((curve && straight && (this.curves.shift() || false)) || (curve && !straight) ? Util.getTargetDirection(this.currentTrack, this.sourceDirection) : this.sourceDirection);
    }
  });


  /*
  AITrain: a train controlled by AI.
   */

  Crafty.c("AITrain", {
    init: function() {
      return this.requires("TrainHead");
    },
    _getSegmentPriority: function(depth, x, y, dir, distance) {
      var cdir, curvedPriority, dropoffPlayer, newx, newy, otherDist, priority, results, sdir, searchPlayer, station, straightPriority, _i, _len, _ref;
      searchPlayer = (this.playerOne ? "playerTwo" : "playerOne");
      dropoffPlayer = (this.playerOne ? "dropoffP1" : "dropoffP2");
      results = AI.checkAlongSegment(x, y, dir);
      cdir = results.endpoint.dir[2];
      sdir = results.endpoint.dir[0];
      newx = results.endpoint.at().x;
      newy = results.endpoint.at().y;
      if (depth > 0) {
        straightPriority = this._getSegmentPriority(depth - 1, newx + Util.dirx(sdir), newy + Util.diry(sdir), sdir, results.distance);
        curvedPriority = this._getSegmentPriority(depth - 1, newx + Util.dirx(cdir), newy + Util.diry(cdir), cdir, results.distance);
      } else {
        straightPriority = 0;
        curvedPriority = 0;
      }
      priority = 0;
      _ref = results.stations;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        station = _ref[_i];
        priority += Math.min(station.population, 100 - this.passengers) + station[dropoffPlayer];
      }
      if (results.trainsFound[searchPlayer]) {
        if (results.trainsFound[searchPlayer].oncoming) {
          otherDist = AI.checkAlongSegment(x, y, Util.opposite(dir)).distance;
          if (otherDist >= distance) {
            priority -= 100;
          }
        } else {
          if (distance < 4) {
            priority -= 50;
          } else if (distance < 8) {
            priority -= 10;
          } else {
            priority -= 5;
          }
        }
      }
      return priority + Math.max(straightPriority + curvedPriority);
    },
    _updateCurrentTrack: function(dir) {
      var backThroughCurve, curve, curvedPriority, decision, f, isCurving, straight, straightPriority, _i, _j, _len, _len1, _ref, _ref1;
      backThroughCurve = this.reversing && !(this._hasCurveOption() && this._hasStraightOption()) && this.currentTrack.dir.length === 3;
      if (backThroughCurve) {
        _ref = this.followers;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          f = _ref[_i];
          f.curves.shift();
        }
      }
      this.currentTrack = Util.trackAt(this.currentTrack.at().x + Util.dirx(dir), this.currentTrack.at().y + Util.diry(dir));
      if (this._arriveAtStation != null) {
        this._arriveAtStation();
      }
      straight = this._hasStraightOption();
      curve = this._hasCurveOption();
      if (straight && curve) {
        straightPriority = this._getSegmentPriority(2, this.currentTrack.at().x + Util.dirx(this.sourceDirection), this.currentTrack.at().y + Util.diry(this.sourceDirection), this.sourceDirection, 0);
        curvedPriority = this._getSegmentPriority(2, this.currentTrack.at().x + Util.dirx(Util.getTargetDirection(this.currentTrack, this.sourceDirection)), this.currentTrack.at().y + Util.diry(Util.getTargetDirection(this.currentTrack, this.sourceDirection)), Util.getTargetDirection(this.currentTrack, this.sourceDirection), 0);
        straightPriority += Math.random() * 20 - 10;
        decision = curvedPriority > straightPriority;
      }
      this.targetDirection = ((straight && curve && decision) || (curve && !straight) ? Util.getTargetDirection(this.currentTrack, this.sourceDirection) : this.sourceDirection);
      if (straight && curve) {
        isCurving = this.isCurving();
        _ref1 = this.followers;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          f = _ref1[_j];
          f.curves.push(isCurving);
        }
      }
    }
  });


  /*
  Track section: a 1x1 piece of track with two or more dirs.
   */

  Crafty.c("TrackSection", {
    init: function() {
      this.requires("2D, Grid");
    },
    associateStation: function(station) {
      this.station = station;
    }
  });


  /*
  Station: associated with a track, has passenger values.
   */

  Crafty.c("Station", {
    init: function() {
      this.population = 0;
      this.dropoffP1 = 0;
      this.dropoffP2 = 0;
      this.popular = false;
      this.requires("2D, Grid");
      this.bind("EnterFrame", function() {
        if (GameState.running && GameClock.hour > 5) {
          this.populate();
        }
      });
    },
    setPopular: function(popular) {
      var letter;
      letter = this.letter;
      this.popular = !this.popular;
      Crafty("spr_" + (this.popular ? "" : "p") + "stop" + this.letter).each(function() {
        this.removeComponent("spr_" + (this.popular ? "" : "p") + "stop" + letter, false);
        this.addComponent("spr_" + (this.popular ? "p" : "") + "stop" + letter);
      });
    },
    setup: function(x, y, dir) {
      this.at(x, y);
      this.setupAttach(dir);
    },
    setupAttach: function(dir) {
      var x, y;
      x = this.at().x;
      y = this.at().y;
      this.facing = dir;
      if (dir === "s") {
        this.attachToTrack(x, y + 1).attachToTrack(x + 1, y + 1);
      } else if (dir === "n") {
        this.attachToTrack(x, y - 1).attachToTrack(x + 1, y - 1);
      } else {
        this.attachToTrack(x + Util.dirx(dir), y).attachToTrack(x + Util.dirx(dir), y + 1);
      }
      this.setupText();
    },
    setupText: function() {
      this.t = [];
      this.previousWaiting = 0;
      this.updateSprites();
    },
    populate: function() {
      if (!this.numStations) {
        this.numStations = Crafty("Station").length;
      }
      if (Math.random() > ((this.popular ? 0.917 : 0.947) + 0.005 * this.numStations)) {
        this.population += 1;
        this.updateSprites();
      }
    },
    attachToTrack: function(x, y) {
      Util.trackAt(x, y).associateStation(this);
      return this;
    },
    updateSprites: function() {
      var pos, remaining, x, y;
      if (!window.HEADLESS_MODE) {
        if (this.population / 12.0 === this.t.length + 1) {
          remaining = Math.min(this.population, 72) - this.t.length * 12;
          pos = this.t.length;
          if (this.facing === "w") {
            x = this._x + 6 * (pos % 2);
            y = this._y + 2 + 8 * pos;
          } else if (this.facing === "e") {
            x = this._x + 20 - 6 * (pos % 2);
            y = this._y + 2 + 8 * pos;
          } else if (this.facing === "n") {
            x = this._x + 2 + 8 * pos;
            y = this._y - 6 + 4 * (pos % 2);
          } else {
            x = this._x + 2 + 8 * pos;
            y = this._y + 12 + 4 * (pos % 2);
          }
          while (remaining >= 12) {
            this.t.push(Crafty.e("StationPerson").attr({
              x: x,
              y: y
            }).fadeIn(this.facing));
            remaining -= 12;
            pos++;
          }
        } else {
          while (this.t.length > this.population / 12) {
            this.t[this.t.length - 1].fadeOut();
            this.t.splice(this.t.length - 1, 1);
          }
        }
        return this;
      }
    }
  });


  /*
   */

  Crafty.c("StationPerson", {
    init: function() {
      this.requires("2D, Canvas, spr_person00");
    },
    fadeIn: function(dir) {
      var i;
      this.alpha = 0;
      this.x -= Util.dirx(dir) * 10;
      this.y -= Util.diry(dir) * 10;
      i = 0;
      while (i <= 9) {
        setTimeout((function(o, dir) {
          return function() {
            o.attr({
              alpha: o.alpha + 0.1,
              x: o.x + Util.dirx(dir),
              y: o.y + Util.diry(dir)
            });
          };
        })(this, dir), i * 50);
        i++;
      }
      return this;
    },
    fadeOut: function() {
      var delay, i;
      delay = Math.random() * 300;
      i = 0;
      while (i <= 9) {
        setTimeout((function(o) {
          return function() {
            o.attr({
              alpha: o.alpha - 0.1,
              y: o._y - 3 * (o.alpha - 0.6)
            });
            if (o.alpha < 0.1) {
              o.destroy();
            }
          };
        })(this), i * 50 + delay);
        i++;
      }
      return this;
    }
  });

  Crafty.c("PlayerScore", {
    init: function() {
      this.requires("2D, DOM, Text").textFont({
        size: "20px",
        family: "Aller"
      });
      this.css({
        textAlign: "center"
      });
      this.display = 0;
      this.attr({
        h: 47,
        w: 200
      });
      this.css({
        padding: 5,
        backgroundColor: "none",
        margin: 10
      });
      this.bind("EnterFrame", function() {
        if (this.display !== this.train.passengers) {
          if (this.display > this.train.passengers) {
            this.display--;
          } else {
            this.display++;
          }
        }
        this.text(this.display + "% Full");
      });
    },
    setup: function() {
      this.bar = Crafty.e("BarController").attr({
        x: this.x + 10,
        y: this.y
      }).attr({
        playerOne: this.playerOne
      }).setup().update();
      this.attach(this.bar);
      this.attr({
        z: 800
      });
    },
    update: function() {
      var p, x;
      if (this.train) {
        x = [];
        p = this.playerOne;
        Crafty("Station").each(function() {
          var t;
          t = (p ? this.dropoffP1 : this.dropoffP2);
          if (t > 1) {
            x.push([t, this.letter, this.popular]);
          }
        });
        x.sort(function(a, b) {
          return b[0] - a[0];
        });
        this.bar.update(this.train.passengers, x);
      }
    }
  });

  Crafty.c("DirectionArrow", {
    init: function() {
      this.requires("Actor, spr_arrowsign").attr({
        z: 1000
      }).bind("EnterFrame", function() {
        if (GameState.running) {
          this.x = this.target.x;
          this.y = this.target.y - 30;
        }
      });
    }
  });

  Crafty.c("Dialog", {
    init: function() {
      this.requires("2D, DOM, Text").css({
        backgroundColor: "#2B281D",
        textAlign: "center",
        border: "4px solid #FFFDE8"
      }).textFont({
        size: "30px",
        family: "Aller"
      }).textColor("#FFFDE8");
      this.attr({
        x: 0,
        y: 112,
        w: 268,
        h: 130
      });
    }
  });

  Crafty.c("ClockController", {
    init: function() {
      GameClock.newDay();
      if (!window.HEADLESS_MODE) {
        this.pauseAvailable = true;
        this.paused = false;
        this.requires("Dialog").attr({
          x: 234,
          y: 492,
          w: 140,
          h: 44
        }).textColor("#84FFEC").textFont({
          size: "43px",
          family: "Minisystem"
        }).css({
          letterSpacing: "-2px",
          border: "4px solid #606060",
          textShadow: "0px 0px 2px #84FFEC"
        });
        this.bind("KeyDown", function(e) {
          if (e.keyCode === Crafty.keys.SPACE && (GameState.running || this.paused)) {
            if (this.pauseAvailable) {
              Crafty.audio.play("select");
              Crafty.e("PauseText");
              this.pauseAvailable = false;
              GameState.running = false;
              this.paused = true;
            } else if (this.paused) {
              Crafty.audio.play("select");
              Crafty("PauseText").teardown();
              Crafty("PauseText").destroy();
              GameState.running = true;
              this.paused = false;
            }
          }
        });
        this.text(GameClock.hour + (GameClock.minute > 9 ? ":" : ":0") + GameClock.minute);
      }
      this.tickDelay = 0;
      this.bind("EnterFrame", function(data) {
        var percentTimePassed;
        percentTimePassed = Math.max(0, (GameClock.hour - 6) / 4 + (GameClock.minute / 240));
        if (GameState.running) {
          this.tickDelay += data.dt / 20;
          GameClock.elapsed += data.dt / 20;
        }
        if (GameState.running && (this.tickDelay > Constants.MINUTE_LENGTH)) {
          GameClock.update();
          this.tickDelay -= Constants.MINUTE_LENGTH;
          if (GameClock.hour === 10) {
            Util.gameOver(false);
          }
          if (!window.HEADLESS_MODE) {
            this.text(GameClock.hour + (GameClock.minute > 9 ? ":" : ":0") + +GameClock.minute);
            Crafty("AmbientLayer").each(function() {
              this.color(Util.sunrise(percentTimePassed));
            });
            Crafty("LightLayer").each(function() {
              this.attr("alpha", 1 - percentTimePassed);
            });
          }
        }
      });
      GameState.running = true;
    }
  });


  /*
  Controls train movement. Makes sure all trains move before checking collision.
   */

  Crafty.c("TrainController", {
    init: function() {
      this.bind("EnterFrame", function(data) {
        if (GameState.running && GameClock.hour > 5) {
          Crafty("Train").each(function() {
            if (this.head.stayDelay > 0) {
              this.head.stayDelay -= 1;
            } else {
              this.moveAlongTrack(this.speed * data.dt / 20);
            }
          });
          Crafty("Train").each(function() {
            this.attr("z", Math.floor(this.y));
            if (this.checkCollision() && GameState.running) {
              Crafty.audio.play("crash");
              Util.gameOver(true);
            }
          });
        }
      });
    }
  });

  Crafty.c("EndingText", {
    init: function() {
      this.requires("Dialog").textFont({
        size: "20px"
      });
      this.display = 0;
      this.attr({
        x: 0,
        y: 112,
        w: 268,
        h: 160
      });
      this.firstText = Crafty.e('DOM, SelectableText').attr({
        x: 230,
        y: 250,
        w: 200,
        h: 30,
        z: 50
      }).textFont({
        size: '17px',
        family: 'Aller'
      }).textColor('#5CC64C').text("Try Again").attr('idx', 0).unselectable();
      this.secondText = Crafty.e('DOM, SelectableText').attr({
        x: 230,
        y: 280,
        w: 200,
        h: 30,
        z: 50
      }).textFont({
        size: '17px',
        family: 'Aller'
      }).textColor('#5CC64C').text("Select Map").attr('idx', 1).unselectable();
      this.arrow = Crafty.e('DOM, SelectArrow').attr({
        x: 190,
        y: 250,
        z: 50,
        callbacks: [
          function() {
            Crafty("TrainController").destroy();
            Crafty.scene("PlayGame");
            return true;
          }, function() {
            Crafty("TrainController").destroy();
            Crafty.scene("SelectMap");
            return true;
          }
        ]
      });
      this.css({
        padding: 20,
        margin: "0px 150px",
        width: 600,
        height: 200,
        boxShadow: "-8px 8px 0px rgba(47,32,16,0.35)"
      });
    }
  });

  Crafty.c("PauseText", {
    init: function() {
      this.requires("Dialog");
      this.text("<br/><br/>Only once a shift!");
      this.css({
        padding: 20,
        margin: "0px 150px",
        width: 600,
        height: 200,
        boxShadow: "-8px 8px 0px rgba(0,0,0,0.4)"
      });
      this.coffee = Crafty.e("2D, DOM, spr_coffee").attr({
        x: this.x + 240,
        y: this.y + 20
      });
      this.space = Crafty.e("2D, DOM, spr_space").attr({
        x: this.x + 260,
        y: this.y + 152
      });
    },
    teardown: function() {
      this.coffee.destroy();
      this.space.destroy();
    }
  });

  Crafty.c("VictoryText", {
    init: function() {
      var p1score, p2score;
      this.requires("EndingText");
      this.attr({
        y: 24,
        h: 380
      });
      this.css({
        height: '350px'
      });
      this.arrow.attr({
        y: 380
      });
      this.firstText.attr({
        y: 380
      });
      this.secondText.attr({
        y: 410
      });
      p1score = 0;
      p2score = 0;
      Crafty("TrainHead").each(function() {
        if (this.playerOne) {
          p1score = this.delivered;
        } else {
          p2score = this.delivered;
        }
      });
      if (p1score !== p2score) {
        this.css({
          border: "4px solid #" + (p1score > p2score ? "E23228" : "4956FF"),
          borderTop: "4px solid #" + (p1score > p2score ? "FF817C" : "848EFF"),
          borderBottom: "4px solid #" + (p1score > p2score ? "B71607" : "1E2DCE")
        });
      }
      GraphTools.placeGraph(p1score === p2score ? Math.random() > 0.5 : (p1score > p2score ? true : false));
      this.text("The morning rush is over!<br/>Passengers delivered:<br/>Red: " + p1score + ", Blue: " + p2score + "<br/>" + (p1score === p2score ? "It's a Draw!" : (p1score > p2score ? "Red" : "Blue") + " Line wins!"));
    }
  });

  Crafty.c("FailureText", {
    init: function() {
      var dialogList;
      this.requires("EndingText");
      if (window.blame) {
        if (window.blamePlayerOne) {
          dialogList = Constants.ENDING_DIALOGS[2];
        } else {
          dialogList = Constants.ENDING_DIALOGS[3];
        }
      } else {
        dialogList = Constants.ENDING_DIALOGS[1];
      }
      this.text(Constants.ENDING_DIALOGS[0][Math.floor(Math.random() * Constants.ENDING_DIALOGS[0].length)] + "<br/>" + dialogList[Math.floor(Math.random() * dialogList.length)]);
    }
  });

  Crafty.c("BarController", {
    init: function() {
      this.requires("2D, Canvas").attr({
        z: 800
      });
    },
    setup: function() {
      var c;
      this.attr({
        h: 20,
        w: 20
      });
      c = (this.playerOne ? "r" : "b");
      this.attach(Crafty.e("2D, Canvas, spr_barback").attr({
        x: this.x,
        y: this.y,
        z: 801
      }));
      this.l = Crafty.e("2D, Canvas, spr_" + c + "barl").attr({
        x: this.x,
        y: this.y,
        z: 801
      });
      this.b = Crafty.e("2D, Canvas, spr_" + c + "bar").attr({
        w: 0,
        x: this.x + 4,
        y: this.y,
        z: 801
      });
      this.r = Crafty.e("2D, Canvas, spr_" + c + "barr").attr({
        x: this.x + 4,
        y: this.y,
        z: 801
      });
      this.attach(this.l);
      this.attach(this.b);
      this.attach(this.r);
      return this;
    },
    update: function(fullness, ticks) {
      var attempt, d, i, previous;
      this.attr({
        x: this.x,
        y: this.y,
        z: 801
      });
      this.l.attr({
        x: this.x,
        y: this.y,
        z: 801
      });
      this.b.attr({
        x: this.x + 4,
        w: (fullness > 4 ? fullness * 2 - 8 : 0),
        z: 801
      });
      this.r.attr({
        x: (fullness > 2 && ticks.length ? this.x - 4 + fullness * 2 : this.x + 4),
        z: 801
      });
      for (i in this.ticks) {
        this.ticks[i].destroy();
      }
      this.ticks = [];
      for (i in this.stops) {
        this.stops[i].destroy();
      }
      this.stops = [];
      d = -2;
      previous = 0;
      for (i in ticks) {
        if (ticks[i][0] > 0) {
          attempt = this.x + d + ((ticks[i][0] | 1) - 1) - 6;
          while (i > 0 && attempt < previous + 12) {
            attempt += 2;
          }
          this.stops.push(Crafty.e("2D, Canvas, spr_" + (ticks[i][2] ? "p" : "") + "stop" + ticks[i][1]).attr({
            x: attempt,
            y: this.y - 22,
            z: 801
          }));
          previous = attempt;
        }
        if (i < ticks.length - 1) {
          d += ticks[i][0] * 2;
          this.ticks.push(Crafty.e("2D, Canvas, spr_" + (this.playerOne ? "r" : "b") + "bart").attr({
            x: this.x + d,
            y: this.y,
            z: 801
          }));
        }
      }
      return this;
    }
  });


  /*
  A line of text to simplify the title screen.
   */

  Crafty.c("TitleText", {
    init: function() {
      this.requires("2D, DOM, Text").attr({
        x: 0,
        w: 616
      }).css({
        textAlign: "center"
      }).textFont({
        size: "17px",
        family: "Aller"
      }).textColor("#FFFDE8");
    }
  });


  /*
  A selector for a menu item.
  Give it an array of callbacks for menu items.
   */

  Crafty.c("SelectArrow", {
    init: function() {
      this.requires("2D, spr_selectarrow");
      this.spaceIcon = Crafty.e('2D, ' + (this.has('DOM') ? 'DOM' : 'Canvas') + ', spr_space').attr({
        x: 150,
        y: -10
      });
      this.attach(this.spaceIcon);
      this.lineHeight = 30;
      this.itemCount = 2;
      this.selectedIndex = 0;
      this.callbacks = [];
      return this.bind("KeyDown", function(e) {
        var zeroPosition;
        zeroPosition = this._y - (this.selectedIndex * this.lineHeight);
        if (e.keyCode === Crafty.keys.P || e.keyCode === Crafty.keys.DOWN_ARROW) {
          this.moveDown();
        } else if (e.keyCode === Crafty.keys.Q || e.keyCode === Crafty.keys.UP_ARROW) {
          this.moveUp();
        } else if (e.keyCode === Crafty.keys.SPACE) {
          if (this.callbacks[this.selectedIndex]) {
            if (this.callbacks[this.selectedIndex]()) {
              Crafty.audio.play("select");
            }
          }
        }
      });
    },
    moveDown: function(n) {
      var count, zeroPosition;
      count = (n ? n : 1);
      zeroPosition = this._y - (this.selectedIndex * this.lineHeight * count);
      Crafty.audio.play("arrowtick");
      this.selectedIndex += count;
      if (this.selectedIndex >= this.itemCount) {
        this.selectedIndex -= this.itemCount;
      }
      return this.attr({
        y: zeroPosition + (this.selectedIndex * this.lineHeight)
      });
    },
    moveUp: function(n) {
      var count, zeroPosition;
      count = (n ? n : 1);
      zeroPosition = this._y - (this.selectedIndex * this.lineHeight * count);
      Crafty.audio.play("arrowtick");
      this.selectedIndex -= count;
      if (this.selectedIndex < 0) {
        this.selectedIndex += this.itemCount;
      }
      return this.attr({
        y: zeroPosition + (this.selectedIndex * this.lineHeight)
      });
    }
  });

  Crafty.c("CheckBox", {
    init: function() {
      this.requires("2D, Canvas, spr_checkbox");
      return this.callback = function() {};
    },
    _setChecked: function(checked) {
      if (this.has('spr_checkbox' + (checked ? '' : 'checked'))) {
        this.removeComponent('spr_checkbox' + (checked ? '' : 'checked'), false);
      }
      return this.addComponent('spr_checkbox' + (checked ? 'checked' : ''));
    },
    refresh: function() {
      return this._setChecked(this.callback());
    }
  });

  Crafty.c("SelectableText", {
    init: function() {
      this.requires("Text, Mouse");
      return this.bind('Click', function() {
        console.log('activating #' + this.idx);
        if (Crafty("SelectArrow").callbacks[this.idx]) {
          if (Crafty("SelectArrow").callbacks[this.idx]()) {
            return Crafty.audio.play("select");
          }
        }
      });
    }
  });

  Crafty.c("Scroller", {
    init: function() {
      this.requires("2D, Canvas, Mouse");
      this.attr({
        x: 0,
        y: 0,
        w: 1000,
        h: 1000,
        offset: 0,
        moving: false,
        firstScroll: false,
        initScroll: 96
      });
      this.bind('MouseDown', function(e) {
        return this.startScroll(e);
      });
      this.bind('MouseMove', function(e) {
        return this.moveScroll(e);
      });
      return this.bind('MouseUp', function(e) {
        return this.endScroll(e);
      });
    },
    startScroll: function(e) {
      this.didMovement = false;
      this.moving = true;
      return this.lasty = e.y;
    },
    moveScroll: function(e) {
      var arrow, _ref;
      if (this.moving) {
        this.didMovement = true;
        window.AAA = this.lasty - e.y;
        this.offset += window.AAA;
        if ((-20 < (_ref = this.offset) && _ref < 410)) {
          Crafty('SelectArrow, spr_selectstn, spr_selectline, _MenuElement').each(function() {
            return this.y -= window.AAA;
          });
        }
        this.lasty = e.y;
        arrow = Crafty("SelectArrow");
        if (arrow.y > 284) {
          arrow.moveUp();
        }
        console.log(arrow.y);
        if (arrow.y < 236.) {
          arrow.moveDown();
          if (this.initScroll > 0) {
            return this.initScroll -= 40;
          }
        }
      }
    },
    endScroll: function() {
      if (this.offset > 410) {
        this.offset = 410;
      }
      if (this.offset < -20) {
        this.offset = -20;
      }
      return this.moving = false;
    }
  });

  $(document).ready(function() {
    window.singlePlayerMode = false;
    window.Brakes = true;
    window.SwapColours = true;
    return window.StationStop = true;
  });

  window.Game = {
    map_grid: {
      width: 22,
      height: 20,
      tile: {
        width: 28,
        height: 28
      }
    },
    width: function() {
      return this.map_grid.width * this.map_grid.tile.width;
    },
    height: function() {
      return this.map_grid.height * this.map_grid.tile.height;
    },
    start: function() {
      window.HEADLESS_MODE = false;
      Crafty.init(Game.width(), Game.height(), "game-stage");
      Crafty.pixelart(true);
      Crafty.background('#2B281D');
      Crafty.scene('Loading');
      return this;
    },
    startHeadless: function() {
      window.HEADLESS_MODE = true;
      Crafty.init(Game.width(), Game.height(), "game-stage");
      Crafty.background('#2B281D');
      $.getJSON("map1.json", function(data) {
        window.selectedMap = data;
        return Crafty.scene('PlayGame');
      });
      return this;
    }
  };

  Crafty.scene('Title', function() {
    self.focus();
    this.letters = "";
    Crafty.e('2D, Canvas, spr_title').attr({
      x: 220
    });
    Crafty.e('TitleText').attr({
      y: 178
    }).text('Compete to deliver more passengers by 10:00 AM.');
    Crafty.e('TitleText').attr({
      y: 228
    }).text('But if the trains collide, nobody wins!');
    Crafty.e('2D, Canvas, spr_keyq').attr({
      x: 230,
      y: 430
    });
    Crafty.e('2D, Canvas, spr_keyp').attr({
      x: 338,
      y: 430
    });
    Crafty.e('2D, Canvas, spr_arrowr').attr({
      x: 230,
      y: 480
    });
    Crafty.e('2D, Canvas, spr_arrowl').attr({
      x: 338,
      y: 480
    });
    Crafty.e('Canvas, SelectArrow').attr({
      x: 190,
      y: 280,
      itemCount: 4,
      callbacks: [
        function() {
          window.singlePlayerMode = false;
          Crafty.scene('SelectMap');
          return true;
        }, function() {
          window.singlePlayerMode = true;
          Crafty.scene('SelectMap');
          return true;
        }, function() {
          Crafty.scene('Instructions');
          return true;
        }, function() {
          Crafty.scene('Options');
          return true;
        }
      ]
    });
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 230,
      y: 280,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Start 2-Player").attr('idx', 0);
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 230,
      y: 310,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Start Vs. AI").attr('idx', 1);
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 230,
      y: 340,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Instructions").attr('idx', 2);
    return Crafty.e('2D, Canvas, SelectableText').attr({
      x: 230,
      y: 370,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Options").attr('idx', 3);
  });

  Crafty.scene('Loading', function() {
    Crafty.audio.create("get1", "assets/get1.wav");
    Crafty.audio.create("get2", "assets/get2.wav");
    Crafty.audio.create("get3", "assets/get3.wav");
    Crafty.audio.create("crash", "assets/crash.wav");
    Crafty.audio.create("select", "assets/select.wav");
    Crafty.audio.create("arrowtick", "assets/arrowtick.wav");
    Crafty.audio.create("brakeson", "assets/brakeson.wav");
    Crafty.audio.create("brakesoff", "assets/brakesoff.wav");
    Crafty.audio.toggleMute();
    return Crafty.load(['img/ul.png', 'img/ullight.png', 'img/wordart.png', 'img/keys.png', 'img/mapselect.png'], function() {
      Crafty.sprite(28, 'img/ul.png', {
        spr_rtrain: [2, 0],
        spr_rtrainside: [3, 0],
        spr_rtraine: [2, 1],
        spr_rtrainn: [3, 1],
        spr_rtrainw: [4, 1],
        spr_rtrains: [5, 1],
        spr_btrain: [2, 2],
        spr_btrainside: [3, 2],
        spr_btraine: [2, 3],
        spr_btrainn: [3, 3],
        spr_btrainw: [4, 3],
        spr_btrains: [5, 3],
        spr_arrowsign: [3, 4],
        spr_platform: [4, 6],
        spr_platformu: [2, 7, 2, 1],
        spr_platformd: [4, 7, 2, 1],
        spr_platforml: [4, 5, 1, 2],
        spr_platformr: [5, 5, 1, 2]
      });
      Crafty.sprite(4, 12, 'img/bars.png', {
        spr_rbarl: [0, 0],
        spr_rbar: [1, 0],
        spr_rbart: [2, 0],
        spr_rbarr: [3, 0],
        spr_bbarl: [0, 1],
        spr_bbar: [1, 1],
        spr_bbart: [2, 1],
        spr_bbarr: [3, 1]
      });
      Crafty.sprite(16, 16, 'img/stops.png', {
        spr_stopa: [0, 0],
        spr_stopb: [1, 0],
        spr_stopc: [2, 0],
        spr_stopd: [3, 0],
        spr_stope: [4, 0],
        spr_stopf: [5, 0],
        spr_person00: [6, 0],
        spr_pstopa: [0, 1],
        spr_pstopb: [1, 1],
        spr_pstopc: [2, 1],
        spr_pstopd: [3, 1],
        spr_pstope: [4, 1],
        spr_pstopf: [5, 1]
      });
      Crafty.sprite(88, 40, 'img/keys.png', {
        spr_space: [0, 0]
      }, 0, 80, true);
      Crafty.sprite(48, 40, 'img/keys.png', {
        spr_keyp: [0, 0],
        spr_keyq: [0, 1],
        spr_arrowl: [1, 0],
        spr_arrowr: [1, 1]
      });
      Crafty.sprite(200, 12, 'img/barback.png', {
        spr_barback: [0, 0]
      });
      Crafty.sprite(176, 176, 'img/wordart.png', {
        spr_title: [0, 0]
      });
      Crafty.sprite(134, 68, 'img/wordart.png', {
        spr_coffee: [0, 0]
      }, 0, 176, true);
      Crafty.sprite(616, 84, 'img/brushed.png', {
        spr_brushed: [0, 0]
      });
      Crafty.sprite(24, 24, 'img/mapselect.png', {
        spr_selectstn: [0, 0],
        spr_selectarrow: [1, 0],
        spr_selectline: [0, 1],
        spr_selectstn2: [1, 1],
        spr_checkbox: [0, 2],
        spr_checkboxchecked: [1, 2]
      });
      Crafty.sprite(44, 44, 'img/tabletbuttons.png', {
        spr_redbutton: [0, 0],
        spr_bluebutton: [1, 0]
      });
      Crafty.sprite(28, 28, 'img/ullight.png', {
        spr_rtrainlight: [2, 0],
        spr_rtrainsidelight: [3, 0],
        spr_rtrainelight: [2, 1],
        spr_rtrainnlight: [3, 1],
        spr_rtrainwlight: [4, 1],
        spr_rtrainslight: [5, 1],
        spr_btrainlight: [2, 2],
        spr_btrainsidelight: [3, 2],
        spr_btrainelight: [2, 3],
        spr_btrainnlight: [3, 3],
        spr_btrainwlight: [4, 3],
        spr_btrainslight: [5, 3],
        spr_light29: [4, 4],
        spr_light30: [5, 4],
        spr_light33: [2, 5],
        spr_light34: [3, 5],
        spr_light35: [4, 5],
        spr_light36: [5, 5],
        spr_light39: [2, 6],
        spr_light40: [3, 6],
        spr_light41: [4, 6],
        spr_light42: [5, 6],
        spr_light43: [0, 7],
        spr_light44: [1, 7],
        spr_light45: [2, 7],
        spr_light46: [3, 7],
        spr_light47: [4, 7],
        spr_light48: [5, 7],
        spr_light49: [0, 8],
        spr_light50: [1, 8],
        spr_light53: [4, 8],
        spr_light54: [5, 8],
        spr_light62: [1, 10],
        spr_light63: [2, 10],
        spr_light64: [3, 10],
        spr_light67: [0, 11],
        spr_light68: [1, 11],
        spr_light69: [2, 11],
        spr_light73: [0, 12],
        spr_light74: [1, 12],
        spr_light76: [3, 12],
        spr_light79: [0, 13],
        spr_light80: [1, 13]
      });
      Crafty.c('LightLayer');
      Crafty.c('AmbientLayer');
      Crafty.scene('Title');
      return this;
    });
  });

  Crafty.scene('SelectMap', function() {
    var curry, idx, mapCallbackMaker, selectArrow, titleText;
    Crafty.background('#2B281D');
    Crafty.e('2D, DOM, Color').color('#2B281D').attr({
      y: 0,
      x: 0,
      w: 1000,
      h: 130
    });
    Crafty.e('2D, DOM, Color').color('#2B281D').attr({
      y: 410,
      x: 0,
      w: 1000,
      h: 150
    });
    Crafty.e('Scroller');
    Crafty.e('TitleText').text('Select a map:').attr({
      y: 30
    });
    titleText = Crafty.e('TitleText, Keyboard, LevelNameText').text(window.MapList[0][1]).attr({
      y: 86,
      titles: []
    }).textColor('#FFFDE8').textFont({
      size: '30px'
    }).bind('EnterFrame', function() {
      if (Crafty('SelectArrow').y > 284) {
        Crafty('SelectArrow, spr_selectstn, spr_selectline, _MenuElement').each(function() {
          return this.y -= 6;
        });
        return Crafty("Scroller").each(function() {
          return this.offset += 6;
        });
      } else if (Crafty('SelectArrow').y < 236) {
        Crafty('SelectArrow, spr_selectstn, spr_selectline, _MenuElement').each(function() {
          return this.y += 6;
        });
        return Crafty("Scroller").each(function() {
          return this.offset -= 6;
        });
      }
    }).textColor('#FFFDE8');
    curry = 236;
    selectArrow = Crafty.e('Canvas, SelectArrow').attr({
      x: 200,
      y: 236,
      itemCount: window.MapList.length + 1,
      lineHeight: 48
    });
    selectArrow.spaceIcon.attr({
      x: 404
    });
    mapCallbackMaker = function(i) {
      return function() {
        if (!Crafty("Scroller").didMovement) {
          $.getJSON(window.MapList[i][0], function(data) {
            window.selectedMap = data;
            return Crafty.scene('PlayGame');
          });
          return true;
        }
        return false;
      };
    };
    for (idx in window.MapList) {
      Crafty.e('2D, Canvas, spr_selectstn').attr({
        x: 250,
        y: curry
      });
      Crafty.e('2D, Canvas, SelectableText, _MenuElement').attr({
        x: 280,
        y: curry,
        w: 200
      }).textFont({
        size: '17px',
        family: 'Aller'
      }).textColor('#FFFDE8').text(window.MapList[idx][1]).attr('idx', idx);
      Crafty.e('2D, Canvas, spr_selectline').attr({
        x: 250,
        y: curry + 24
      });
      curry += 48;
      selectArrow.callbacks.push(mapCallbackMaker(idx));
      titleText.titles.push(window.MapList[idx][1]);
    }
    Crafty.e('2D, Canvas, spr_selectstn').attr({
      x: 250,
      y: curry
    });
    Crafty.e('2D, Canvas, SelectableText, _MenuElement').attr({
      x: 280,
      y: curry,
      w: 200
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#E23228').text("Back to Title").attr('idx', ++idx);
    titleText.titles.push("Back to Title");
    selectArrow.callbacks.push(function() {
      Crafty.scene('Title');
      return true;
    });
    Crafty.e('2D, DOM, spr_keyq').attr({
      x: 230,
      y: 430
    });
    Crafty.e('2D, DOM, spr_keyp').attr({
      x: 338,
      y: 430
    });
    Crafty.e('2D, DOM, spr_arrowr').attr({
      x: 230,
      y: 480
    });
    Crafty.e('2D, DOM, spr_arrowl').attr({
      x: 338,
      y: 480
    });
    return Crafty("SelectableText").each(function() {
      this.bind('MouseDown', function(e) {
        return Crafty("Scroller").startScroll(e);
      });
      this.bind('MouseMove', function(e) {
        return Crafty("Scroller").moveScroll(e);
      });
      return this.bind('MouseUp', function(e) {
        return Crafty("Scroller").endScroll(e);
      });
    });
  });

  Crafty.scene('PlayGame', function() {
    var builder;
    Crafty.background('rgb(80, 160, 40)');
    builder = Crafty.e((window.HEADLESS_MODE ? "" : "2D, Canvas, ") + "TiledMapBuilder");
    builder.setMapDataSource(window.selectedMap).createWorld(Util.setupFromTiled);
    Crafty.e('TrainController');
    Crafty.e('ClockController');
    if (!window.HEADLESS_MODE) {
      Crafty.e('2D, Canvas, spr_brushed').attr({
        w: 616,
        h: 84,
        y: 476,
        z: 800
      });
      Crafty.e('2D, Canvas, Color, AmbientLayer').attr({
        x: 0,
        y: 0,
        z: 600,
        h: 1000,
        w: 1000
      }).color('rgba(3,29,51,0.5)');
    }
    Util.assignStations();
    if (window.TabletControls) {
      Crafty.e('2D, Canvas, Mouse, spr_redbutton').bind('MouseDown', function() {
        if (GameState.running) {
          Crafty.audio.play('brakeson');
          return Crafty("PlayerTrain RedTrain")._setBraking(true);
        }
      }).bind('MouseUp', function() {
        if (GameState.running) {
          Crafty.audio.play('brakesoff');
          return Crafty("PlayerTrain RedTrain")._setBraking(false);
        }
      }).bind('MouseOut', function() {
        if (GameState.running) {
          if (Crafty("PlayerTrain RedTrain").isBraking()) {
            Crafty.audio.play('brakesoff');
          }
          return Crafty("PlayerTrain RedTrain")._setBraking(false);
        }
      }).attr({
        x: 4,
        y: 512,
        z: 810
      });
      if (!window.singlePlayerMode) {
        Crafty.e('2D, Canvas, Mouse, spr_bluebutton').bind('MouseDown', function() {
          if (GameState.running) {
            Crafty.audio.play('brakeson');
            return Crafty("PlayerTrain BlueTrain")._setBraking(true);
          }
        }).bind('MouseUp', function() {
          if (GameState.running) {
            Crafty.audio.play('brakesoff');
            return Crafty("PlayerTrain BlueTrain")._setBraking(false);
          }
        }).bind('MouseOut', function() {
          if (GameState.running) {
            if (Crafty("PlayerTrain BlueTrain").isBraking()) {
              Crafty.audio.play('brakesoff');
            }
            return Crafty("PlayerTrain BlueTrain")._setBraking(false);
          }
        }).attr({
          x: 568,
          y: 512,
          z: 810
        });
      }
      return Crafty("PlayerScore").each(function() {
        return this.attr('y', 490);
      });
    }
  });

  Crafty.scene('Options', function() {
    var selectArrow;
    selectArrow = Crafty.e('Canvas, SelectArrow').attr({
      x: 170,
      y: 280,
      itemCount: 7,
      callbacks: [
        function() {
          Crafty.audio.toggleMute();
          Crafty('CheckBox').get(0).refresh();
          return true;
        }, function() {
          window.SwapColours = !window.SwapColours;
          Crafty('CheckBox').get(1).refresh();
          return true;
        }, function() {
          window.Brakes = !window.Brakes;
          Crafty('CheckBox').get(2).refresh();
          return true;
        }, function() {
          window.StationStop = !window.StationStop;
          Crafty('CheckBox').get(3).refresh();
          return true;
        }, function() {
          window.TabletControls = !window.TabletControls;
          Crafty('CheckBox').get(4).refresh();
          return true;
        }, function() {
          window.Blame = !window.Blame;
          Crafty('CheckBox').get(5).refresh();
          return true;
        }, function() {
          Crafty.scene('Title');
          return true;
        }
      ]
    });
    selectArrow.spaceIcon.attr({
      x: 398
    });
    Crafty.e('TitleText').attr({
      y: 100
    }).text("Options").textFont({
      size: '30px'
    });
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 210,
      y: 280,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Sound On").attr('idx', 0);
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 210,
      y: 310,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Randomize Colours").attr('idx', 1);
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 210,
      y: 340,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Brakes").attr('idx', 2);
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 210,
      y: 370,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Station Stop").attr('idx', 3);
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 210,
      y: 400,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Tablet Controls").attr('idx', 4);
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 210,
      y: 430,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').text("Assign Blame").attr('idx', 5);
    Crafty.e('2D, Canvas, SelectableText').attr({
      x: 210,
      y: 460,
      w: 200,
      z: 50
    }).textFont({
      size: '17px',
      family: 'Aller'
    }).textColor('#5CC64C').textColor('#E23228').text("Back to Title").attr('idx', 6);
    Crafty.e('2D, Canvas, CheckBox').attr({
      x: 366,
      y: 280,
      callback: function() {
        return !Crafty.audio.muted;
      }
    }).refresh();
    Crafty.e('2D, Canvas, CheckBox').attr({
      x: 366,
      y: 310,
      callback: function() {
        return window.SwapColours;
      }
    }).refresh();
    Crafty.e('2D, Canvas, CheckBox').attr({
      x: 366,
      y: 340,
      callback: function() {
        return window.Brakes;
      }
    }).refresh();
    Crafty.e('2D, Canvas, CheckBox').attr({
      x: 366,
      y: 370,
      callback: function() {
        return window.StationStop;
      }
    }).refresh();
    Crafty.e('2D, Canvas, CheckBox').attr({
      x: 366,
      y: 400,
      callback: function() {
        return window.TabletControls;
      }
    }).refresh();
    return Crafty.e('2D, Canvas, CheckBox').attr({
      x: 366,
      y: 430,
      callback: function() {
        return window.Blame;
      }
    }).refresh();
  });

  Crafty.scene('Instructions', function() {
    Crafty.e('2D, Canvas, spr_keyq').attr({
      x: 194,
      y: 180
    });
    Crafty.e('2D, DOM, Text').attr({
      x: 161,
      y: 228,
      w: 200
    }).text('Red Train').textFont({
      size: '26px',
      family: 'Aller'
    }).textColor('#E23228');
    Crafty.e('2D, Canvas, spr_keyp, nobots').attr({
      x: 375,
      y: 180
    });
    Crafty.e('2D, DOM, Text, nobots').attr({
      x: 338,
      y: 228,
      w: 200
    }).text('Blue Train').textFont({
      size: '26px',
      family: 'Aller'
    }).textColor('#4956FF');
    Crafty.e('TitleText').attr({
      y: 136
    }).text('Hold your key to slow down and turn at junctions:');
    Crafty.e('TitleText').attr({
      y: 280
    }).text('Pick up and drop off passengers by driving through stations.');
    Crafty.e('TitleText').attr({
      y: 310
    }).text('Passenger destinations are shown at the bottom.');
    Crafty.e('TitleText').attr({
      y: 340
    }).text('Be aware of your opponent\'s position to avoid collisions.');
    Crafty.e('2D, Canvas, Mouse, spr_space').attr({
      x: 264,
      y: 400
    }).bind('KeyDown', function(e) {
      if (e.keyCode === Crafty.keys.SPACE) {
        Crafty.audio.play('select');
        return Crafty.scene('Title');
      }
    }).bind('MouseDown', function(e) {
      Crafty.audio.play('select');
      return Crafty.scene('Title');
    });
    return Crafty.e('TitleText, Mouse').attr({
      y: 444,
      h: 30
    }).text('Back').bind('MouseDown', function(e) {
      Crafty.audio.play('select');
      return Crafty.scene('Title');
    });
  });

  window.Util = {
    opposite: function(dir) {
      switch (dir) {
        case 'e':
          return 'w';
        case 'w':
          return 'e';
        case 'n':
          return 's';
        default:
          return 'n';
      }
    },
    endAngle: function(dir) {
      switch (dir) {
        case 'e':
          return 0;
        case 's':
          return Math.PI / 2;
        case 'w':
          return Math.PI;
        default:
          return Math.PI * 3 / 2;
      }
    },
    trackAt: function(x, y) {
      var result;
      result = null;
      Crafty("TrackSection").each(function() {
        if (this.at().x === x && this.at().y === y) {
          return result = this;
        }
      });
      return result;
    },
    dirx: function(dir) {
      switch (dir) {
        case 'e':
          return 1;
        case 'w':
          return -1;
        default:
          return 0;
      }
    },
    diry: function(dir) {
      switch (dir) {
        case 'n':
          return -1;
        case 's':
          return 1;
        default:
          return 0;
      }
    },
    heading: function(x, y) {
      if (x === -1) {
        return 'w';
      } else if (x === 1) {
        return 'e';
      } else if (y === -1) {
        return 'n';
      } else if (y === 1) {
        return 's';
      } else {
        return null;
      }
    },
    getTargetDirection: function(track, dir) {
      var idx;
      idx = track.dir.indexOf(Util.opposite(dir));
      if (idx === track.dir.length - 1) {
        return track.dir[idx - 1];
      } else {
        return track.dir[idx + 1];
      }
    },
    assignStations: function() {
      var i;
      i = 0;
      return Crafty('Station').each(function() {
        if (!window.HEADLESS_MODE) {
          Crafty.e('2D, Canvas, spr_stop' + ['a', 'b', 'c', 'd', 'e', 'f'][i]).attr({
            x: this.x + (this.facing === 'e' || this.facing === 'w' ? 6 : 20),
            y: this.y - 20,
            z: 999
          });
        }
        return this.letter = ['a', 'b', 'c', 'd', 'e', 'f'][i++];
      });
    },
    gameOver: function(failure) {
      if (GameState.running) {
        GameState.running = false;
        if (failure) {
          setTimeout(function() {
            return Crafty.e('FailureText');
          }, 1000);
          return this;
        } else {
          return setTimeout(function() {
            return Crafty.e('VictoryText');
          }, 800);
        }
      }
    },
    createTrain: function(x, y, playerOne, dir, cars) {
      var front, i, letter, temp, train, _i, _j, _len, _ref, _ref1, _results;
      if (cars == null) {
        cars = 3;
      }
      letter = (playerOne ? 'r' : 'b');
      train = Crafty.e((playerOne || !window.singlePlayerMode ? 'PlayerTrain' : 'AITrain') + (playerOne ? ', RedTrain' : ', BlueTrain')).at(x, y).attr('playerOne', playerOne).attr('sourceDirection', dir).attr('targetDirection', dir).findTrack();
      if (playerOne || !window.singlePlayerMode) {
        train.bindKeyboardTurn((playerOne ? Crafty.keys.Q : Crafty.keys.P));
      }
      train.moveAlongTrack(0);
      train.followers = [];
      front = train;
      train.attr('head', train);
      _ref1 = (cars > 1 ? (function() {
        _results = [];
        for (var _j = 2, _ref = Math.max(2, cars); 2 <= _ref ? _j <= _ref : _j >= _ref; 2 <= _ref ? _j++ : _j--){ _results.push(_j); }
        return _results;
      }).apply(this) : []);
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        i = _ref1[_i];
        temp = Crafty.e('FollowTrain' + (playerOne ? ', RedTrain' : ', BlueTrain')).at(x, y).attr('playerOne', playerOne).attr('sourceDirection', dir).attr('targetDirection', dir).findTrack().attr('front', front).attr('head', train);
        if (i === 2) {
          temp.addComponent("CarryingTrain");
        }
        front = temp;
        train.followers.push(front);
        front.moveAlongTrack(-22 * (i - 1));
        front.distanceTraveled = 0;
      }
      return train;
    },
    setupFromTiled: function(tiledmap) {
      var actuallySwapColours, firstTrain, prop, secondTrain, tile, tilecode, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1, _ref2, _ref3;
      actuallySwapColours = window.SwapColours && Math.random() > 0.5;
      _ref = tiledmap.getEntitiesInLayer('Tracks');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        tile = _ref[_i];
        tile.addComponent('TrackSection');
        for (prop in tile.__c) {
          if (prop.substring(0, 4) === 'Tile') {
            tilecode = prop.substring(4);
            switch (tilecode) {
              case '1':
                tile.dir = ['e', 's'];
                break;
              case '2':
                tile.dir = ['w', 's'];
                break;
              case '7':
                tile.dir = ['n', 'e'];
                break;
              case '8':
                tile.dir = ['n', 'w'];
                break;
              case '13':
                tile.dir = ['e', 'w'];
                break;
              case '14':
                tile.dir = ['n', 's'];
                break;
              case '19':
                tile.dir = ['w', 'e', 'n'];
                break;
              case '20':
                tile.dir = ['w', 'e', 's'];
                break;
              case '25':
                tile.dir = ['s', 'n', 'e'];
                break;
              case '26':
                tile.dir = ['s', 'n', 'w'];
                break;
              case '27':
                tile.dir = ['s', 'n', 'e', 'w'];
                break;
              case '31':
                tile.dir = ['e', 'w', 's'];
                break;
              case '32':
                tile.dir = ['e', 'w', 'n'];
                break;
              case '37':
                tile.dir = ['n', 's', 'e'];
                break;
              case '38':
                tile.dir = ['n', 's', 'w'];
            }
          }
        }
      }
      _ref1 = tiledmap.getEntitiesInLayer('Stations');
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        tile = _ref1[_j];
        for (prop in tile.__c) {
          if (prop.substring(0, 4) === 'Tile') {
            tilecode = prop.substring(4);
            if ((tilecode === '29' || tilecode === '30' || tilecode === '33' || tilecode === '34' || tilecode === '35' || tilecode === '36' || tilecode === '39' || tilecode === '40' || tilecode === '41' || tilecode === '42' || tilecode === '43' || tilecode === '44' || tilecode === '45' || tilecode === '46' || tilecode === '47' || tilecode === '48' || tilecode === '49' || tilecode === '50' || tilecode === '53' || tilecode === '54' || tilecode === '62' || tilecode === '63' || tilecode === '64') && (!window.HEADLESS_MODE)) {
              Crafty.e('2D, Canvas, LightLayer, spr_light' + tilecode).attr({
                x: tile.x,
                y: tile.y,
                z: 801
              });
            }
            switch (tilecode) {
              case '35':
                tile.addComponent('Station').setupAttach('w');
                break;
              case '36':
                tile.addComponent('Station').setupAttach('e');
                break;
              case '45':
                tile.addComponent('Station').setupAttach('n');
                break;
              case '47':
                tile.addComponent('Station').setupAttach('s');
            }
          }
        }
      }
      _ref2 = tiledmap.getEntitiesInLayer('Trains');
      for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
        tile = _ref2[_k];
        tile.addComponent('Actor');
        for (prop in tile.__c) {
          if (prop.substring(0, 4) === 'Tile') {
            tilecode = prop.substring(4);
            switch (tilecode) {
              case '9':
                firstTrain = Util.createTrain(tile.at().x, tile.at().y, !actuallySwapColours, 'e');
                break;
              case '10':
                firstTrain = Util.createTrain(tile.at().x, tile.at().y, !actuallySwapColours, 'n');
                break;
              case '11':
                firstTrain = Util.createTrain(tile.at().x, tile.at().y, !actuallySwapColours, 'w');
                break;
              case '12':
                firstTrain = Util.createTrain(tile.at().x, tile.at().y, !actuallySwapColours, 's');
                break;
              case '21':
                secondTrain = Util.createTrain(tile.at().x, tile.at().y, actuallySwapColours, 'e');
                break;
              case '22':
                secondTrain = Util.createTrain(tile.at().x, tile.at().y, actuallySwapColours, 'n');
                break;
              case '23':
                secondTrain = Util.createTrain(tile.at().x, tile.at().y, actuallySwapColours, 'w');
                break;
              case '24':
                secondTrain = Util.createTrain(tile.at().x, tile.at().y, actuallySwapColours, 's');
            }
            tile.destroy();
          }
        }
      }
      if (tiledmap.getEntitiesInLayer('Props')) {
        _ref3 = tiledmap.getEntitiesInLayer('Props');
        for (_l = 0, _len3 = _ref3.length; _l < _len3; _l++) {
          tile = _ref3[_l];
          tile.attr('z', 9);
          for (prop in tile.__c) {
            if (prop.substring(0, 4) === 'Tile') {
              tilecode = prop.substring(4);
              if (tilecode === '29' || tilecode === '30' || tilecode === '33' || tilecode === '34' || tilecode === '25' || tilecode === '36' || tilecode === '39' || tilecode === '40' || tilecode === '41' || tilecode === '42' || tilecode === '43' || tilecode === '44' || tilecode === '45' || tilecode === '46' || tilecode === '47' || tilecode === '48' || tilecode === '49' || tilecode === '50' || tilecode === '53' || tilecode === '54' || tilecode === '62' || tilecode === '63' || tilecode === '64' || tilecode === '67' || tilecode === '68' || tilecode === '69' || tilecode === '73' || tilecode === '74' || tilecode === '76' || tilecode === '79' || tilecode === '80') {
                Crafty.e('2D, Canvas, LightLayer, spr_light' + tilecode).attr({
                  x: tile.x,
                  y: tile.y,
                  z: 801
                });
              }
            }
          }
        }
      }
      if (!window.HEADLESS_MODE) {
        if (firstTrain) {
          Crafty.e('PlayerScore').attr({
            "x": 0,
            "y": 512
          }).attr({
            train: (actuallySwapColours ? secondTrain : firstTrain),
            playerOne: true
          }).setup();
        }
        if (secondTrain) {
          return Crafty.e('PlayerScore').attr({
            "x": 392,
            "y": 512
          }).attr({
            train: (actuallySwapColours ? firstTrain : secondTrain),
            playerOne: false
          }).setup();
        }
      }
    },
    sunrise: function(percent) {
      if (percent < 0.25) {
        return 'rgba(' + (3 + Math.floor(percent * 400)) + ',' + (29 + Math.floor(percent * 200)) + ',51,' + (1 - percent) / 2 + ')';
      } else {
        return 'rgba(' + (103 - Math.floor((percent - 0.25) * 300)) + ',' + (79 + Math.floor((percent - 0.25) * 60)) + ',' + (51 + Math.floor((percent - 0.25) * 150)) + ',' + (1 - percent) / 2 + ')';
      }
    }
  };

  window.Constants = {
    DIR_PREFIXES: ['n', 'e', 'w', 's'],
    COLLISION_SIZE: 22,
    TILE_HALF: 14,
    CURVE_QUARTER: 28 * Math.PI / 4,
    ENDING_DIALOGS: [['Oh no!', 'The trains collided!', 'You caused an accident!', 'What a disaster!', 'That wasn\'t supposed to happen!'], ['If anyone asks, you weren\'t having a competition.', 'You know, this is really everyone\'s fault.', 'You know, this is really everyone\'s fault. Even the passengers.', 'Some passengers were jostled, many more were late for work.', 'Remember, you\'re supposed to AVOID each other.', 'What kind of urban planner designed this place, anyway?!'], ['If only the red train had planned ahead a bit better...'], ['This one\'s definitely the blue train\'s fault...']],
    MAX_PASSENGERS: 100,
    FULL_SPEED: 1.75,
    REDUCED_SPEED: 0.875,
    TILE_JUMP_LIMIT: 5,
    MINUTE_LENGTH: 24
  };

  window.GameState = {
    running: false
  };

  window.GameClock = {
    elapsed: 0,
    newDay: function() {
      this.hour = 5;
      return this.minute = 55;
    },
    update: function() {
      if (this.minute >= 59) {
        this.hour += 1;
        return this.minute = 0;
      } else {
        return this.minute += 1;
      }
    }
  };

  window.AI = {
    checkAlongSegment: function(x, y, dir) {
      var dist, heading, stations, track, trainPosition, trainPositions, trainPresences, _i, _len;
      trainPositions = [];
      stations = [];
      trainPresences = {
        playerOne: false,
        playerTwo: false
      };
      Crafty("Train").each(function() {
        return trainPositions.push([this.currentTrack.at().x, this.currentTrack.at().y, this.playerOne, this.targetDirection]);
      });
      dist = 0;
      heading = dir;
      track = Util.trackAt(x, y);
      while (track.dir.length !== 3 || track.dir[1] !== Util.opposite(heading)) {
        if (track.station) {
          stations.push(track.station);
        }
        if (track.dir.length === 2) {
          heading = (Util.opposite(heading) === track.dir[0] ? track.dir[track.dir.length - 1] : track.dir[0]);
        } else if (track.dir.length === 3) {
          heading = track.dir[1];
        }
        dist += 1;
        x += Util.dirx(heading);
        y += Util.diry(heading);
        for (_i = 0, _len = trainPositions.length; _i < _len; _i++) {
          trainPosition = trainPositions[_i];
          if (trainPosition[0] === x && trainPosition[1] === y) {
            trainPresences[(trainPosition[2] ? "playerOne" : "playerTwo")] = {
              oncoming: trainPosition[3] === Util.opposite(heading),
              distance: dist
            };
          }
        }
        track = Util.trackAt(x, y);
      }
      return {
        distance: dist,
        endpoint: track,
        trainsFound: trainPresences,
        stations: stations
      };
    }
  };

  window.GraphTools = {
    drawGraph: function(data, target, options) {
      var c2, count, dataCopy, i, tickPoint, tr, y;
      dataCopy = data.slice();
      data.unshift([0, 0, 0]);
      dataCopy.push([240, 0, 0]);
      c2 = target.getContext("2d");
      c2.strokeStyle = options.color;
      c2.fillStyle = "rgba" + options.color.slice(3, -1) + ",0.5)";
      c2.lineWidth = 2;
      c2.beginPath();
      y = 100;
      c2.moveTo(0, y);
      count = 0;
      tr = void 0;
      for (i in dataCopy) {
        tr = dataCopy[i];
        count += tr[1] - tr[2];
        y -= tr[1] * options.y;
        c2.lineTo(tr[0] * options.x, y);
      }
      y += count * options.y;
      c2.lineTo(tr[0] * options.x, y);
      tickPoint = [tr[0] * options.x, y];
      dataCopy.reverse();
      for (i in dataCopy) {
        tr = dataCopy[i];
        y += tr[2] * options.y;
        if (dataCopy[parseInt(i) + 1]) {
          c2.lineTo(dataCopy[parseInt(i) + 1][0] * options.x, y);
        }
      }
      c2.closePath();
      c2.fill();
      c2.beginPath();
      c2.moveTo(tickPoint[0], tickPoint[1]);
      y = tickPoint[1];
      for (i in dataCopy) {
        tr = dataCopy[i];
        y += tr[2] * options.y;
        if (dataCopy[parseInt(i) + 1]) {
          c2.lineTo(dataCopy[parseInt(i) + 1][0] * options.x, y);
        }
      }
      c2.stroke();
      c2.beginPath();
      c2.moveTo(tickPoint[0], tickPoint[1]);
      c2.lineTo(tickPoint[0] + 8, tickPoint[1]);
      c2.closePath();
      c2.stroke();
    },
    drawHourLines: function(target, options) {
      var c2, i;
      c2 = target.getContext("2d");
      c2.translate(2, 0);
      c2.strokeStyle = "rgba(255,253,232,0.5)";
      c2.lineWidth = 1;
      i = 0;
      while (i <= 4) {
        c2.beginPath();
        c2.moveTo(60 * i * options.x, 0);
        c2.lineTo(60 * i * options.x, 500 * options.y);
        c2.closePath();
        c2.stroke();
        i++;
      }
    },
    drawPixelated: function(img, context, zoom, x, y) {
      var a, b, ctx, g, i, idata, r, x2, y2;
      if (!zoom) {
        zoom = 4;
      }
      if (!x) {
        x = 0;
      }
      if (!y) {
        y = 0;
      }
      ctx = document.createElement("canvas").getContext("2d");
      ctx.width = img.width;
      ctx.height = img.height;
      ctx.drawImage(img, 0, 0);
      idata = ctx.getImageData(0, 0, img.width, img.height).data;
      context.fillStyle = "#2B281D";
      context.fillRect(-10, -10, 1000, 1000);
      x2 = 0;
      while (x2 < img.width) {
        y2 = 0;
        while (y2 < img.height) {
          i = (y2 * img.width + x2) * 4;
          r = idata[i];
          g = idata[i + 1];
          b = idata[i + 2];
          a = idata[i + 3];
          context.fillStyle = "rgba(" + r + "," + g + "," + b + "," + (a / 255) + ")";
          context.fillRect(x + x2 * zoom, y + y2 * zoom, zoom, zoom);
          ++y2;
        }
        ++x2;
      }
    },
    drawGraphContents: function(target, p1wins) {
      var blueT, c2, redT;
      c2 = target.getContext("2d");
      redT = void 0;
      blueT = void 0;
      Crafty("CarryingTrain").each(function() {
        if (this.playerOne) {
          redT = this.trans;
        } else {
          blueT = this.trans;
        }
      });
      this.drawHourLines(target, {
        x: 0.4,
        y: 0.2
      });
      this.drawGraph((p1wins ? blueT : redT), target, {
        color: (p1wins ? "rgb(73,86,255)" : "rgb(226,50,40)"),
        x: 0.4,
        y: 0.2
      });
      this.drawGraph((p1wins ? redT : blueT), target, {
        color: (p1wins ? "rgb(226,50,40)" : "rgb(73,86,255)"),
        x: 0.4,
        y: 0.2
      });
      this.drawPixelated(target, target.getContext("2d"), 2);
    },
    placeGraph: function(p1wins) {
      setTimeout((function() {
        var fff;
        fff = $(".VictoryText");
        $("<canvas id=\"graph\" height=220 width=220></canvas>").appendTo(fff);
        GraphTools.drawGraphContents(document.getElementById("graph"), p1wins);
      }), 50);
    },
    idataById: {},
    lastImageId: 0
  };

  $.getJSON('./maps.json', function(mapListSource) {
    return window.MapList = mapListSource;
  });

}).call(this);
