// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    window.singlePlayerMode = false;
    $(window).keydown(function(e) {
      if (!window.dontGoAway && !($(e.target).is("textarea, a"))) {
        $('#display-manual').hide();
        $('#display-design').hide();
      }
      window.dontGoAway = false;
      return true;
    });
    $("body").click(function(e) {
      if (!($(e.target).is("textarea, a"))) {
        $('#display-manual').hide();
        return $('#display-design').hide();
      }
    });
    $('.linkbar a:nth-child(1)').click(function() {
      if ($('#display-manual:visible').length) {
        $('#display-manual').hide();
      } else {
        $('#display-design').hide();
        $('#display-manual').show();
      }
      return false;
    });
    return $('.linkbar a:nth-child(2)').click(function() {
      if ($('#display-design:visible').length) {
        $('#display-design').hide();
      } else {
        $('#display-manual').hide();
        $('#display-design').show();
      }
      return false;
    });
  });

  window.Game = {
    map_grid: {
      width: 22,
      height: 20,
      tile: {
        width: 28,
        height: 28
      }
    },
    width: function() {
      return this.map_grid.width * this.map_grid.tile.width;
    },
    height: function() {
      return this.map_grid.height * this.map_grid.tile.height;
    },
    start: function() {
      Crafty.init(Game.width(), Game.height(), "game-stage");
      Crafty.background('#2B281D');
      Crafty.scene('Loading');
      return this;
    }
  };

}).call(this);
